# fly.toml app configuration file generated for presentation-generator-fragrant-mountain-1643 on 2025-03-14T01:30:42+05:45
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'presentation-generator-fragrant-mountain-1643'
primary_region = 'sin'

[build]

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 1
processes = ['app']


[[vm]]
size = 'shared-cpu-2x'
memory = '2gb'
cpu_kind = 'shared'
cpus = 2
